pipelines:
  master:
    - parallel:
      - step:
          name: 'Deploy to staging'
          deployment: staging
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."